/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jaddon.jlog;

import jaddon.controller.StaticStandard;
import javax.imageio.ImageIO;

/**
 *
 * @author Paul
 */
public class Console extends javax.swing.JFrame {

    public static final String ICON = "/jaddon/icons/Farm-Fresh_application_xp_terminal.png";
    
    /**
     * Creates new form Console
     */
    public Console() {
        initComponents();
        try {
            setIconImage(ImageIO.read(Console.class.getResourceAsStream(ICON)));
        } catch (Exception ex) {
            StaticStandard.logErr("Error while loading console icon: " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        textfield = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        scrollpane = new javax.swing.JScrollPane();
        textpane = new javax.swing.JTextPane();
        menubar = new javax.swing.JMenuBar();
        M1 = new javax.swing.JMenu();
        M1I3 = new javax.swing.JMenuItem();
        M1S2 = new javax.swing.JPopupMenu.Separator();
        M1I4 = new javax.swing.JMenuItem();
        M1S1 = new javax.swing.JPopupMenu.Separator();
        M1I2 = new javax.swing.JMenuItem();
        M1I1 = new javax.swing.JMenuItem();
        M2 = new javax.swing.JMenu();
        M2C5 = new javax.swing.JCheckBoxMenuItem();
        M2C6 = new javax.swing.JCheckBoxMenuItem();
        M2C7 = new javax.swing.JCheckBoxMenuItem();
        M2C8 = new javax.swing.JCheckBoxMenuItem();
        M2C9 = new javax.swing.JCheckBoxMenuItem();
        M2S1 = new javax.swing.JPopupMenu.Separator();
        M2C1 = new javax.swing.JCheckBoxMenuItem();
        M2C2 = new javax.swing.JCheckBoxMenuItem();
        M2C3 = new javax.swing.JCheckBoxMenuItem();
        M2S2 = new javax.swing.JPopupMenu.Separator();
        M2C4 = new javax.swing.JCheckBoxMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button.setText("Enter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        textpane.setEditable(false);
        scrollpane.setViewportView(textpane);

        getContentPane().add(scrollpane, java.awt.BorderLayout.CENTER);

        M1.setText("File");

        M1I3.setText("Reload");
        M1.add(M1I3);
        M1.add(M1S2);

        M1I4.setText("Save As");
        M1.add(M1I4);
        M1.add(M1S1);

        M1I2.setText("Restart");
        M1.add(M1I2);

        M1I1.setText("Exit");
        M1.add(M1I1);

        menubar.add(M1);

        M2.setText("Options");

        M2C5.setSelected(true);
        M2C5.setText("Show Normal");
        M2.add(M2C5);

        M2C6.setSelected(true);
        M2C6.setText("Show Error");
        M2.add(M2C6);

        M2C7.setSelected(true);
        M2C7.setText("Show Input");
        M2.add(M2C7);

        M2C8.setSelected(true);
        M2C8.setText("Show Command");
        M2.add(M2C8);

        M2C9.setSelected(true);
        M2C9.setText("Show Low");
        M2.add(M2C9);
        M2.add(M2S1);

        M2C1.setSelected(true);
        M2C1.setText("Show Timestamp");
        M2.add(M2C1);

        M2C2.setSelected(true);
        M2C2.setText("Show Appearance");
        M2.add(M2C2);

        M2C3.setSelected(true);
        M2C3.setText("Show Level");
        M2.add(M2C3);
        M2.add(M2S2);

        M2C4.setSelected(true);
        M2C4.setText("Enable Debug Mode");
        M2.add(M2C4);

        menubar.add(M2);

        setJMenuBar(menubar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Console.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Console.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Console.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Console.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Console().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu M1;
    public javax.swing.JMenuItem M1I1;
    public javax.swing.JMenuItem M1I2;
    public javax.swing.JMenuItem M1I3;
    public javax.swing.JMenuItem M1I4;
    private javax.swing.JPopupMenu.Separator M1S1;
    private javax.swing.JPopupMenu.Separator M1S2;
    public javax.swing.JMenu M2;
    public javax.swing.JCheckBoxMenuItem M2C1;
    public javax.swing.JCheckBoxMenuItem M2C2;
    public javax.swing.JCheckBoxMenuItem M2C3;
    public javax.swing.JCheckBoxMenuItem M2C4;
    public javax.swing.JCheckBoxMenuItem M2C5;
    public javax.swing.JCheckBoxMenuItem M2C6;
    public javax.swing.JCheckBoxMenuItem M2C7;
    public javax.swing.JCheckBoxMenuItem M2C8;
    public javax.swing.JCheckBoxMenuItem M2C9;
    private javax.swing.JPopupMenu.Separator M2S1;
    private javax.swing.JPopupMenu.Separator M2S2;
    public javax.swing.JButton button;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenuBar menubar;
    public javax.swing.JScrollPane scrollpane;
    public javax.swing.JTextField textfield;
    public javax.swing.JTextPane textpane;
    // End of variables declaration//GEN-END:variables
}
