/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jaddon.jlog;

import jaddon.controller.StaticStandard;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.time.Instant;
import javax.swing.JFileChooser;

/**
 *
 * @author Paul
 */
public class WizardSaveAs extends javax.swing.JDialog implements ActionListener, WindowListener {
    
    private LogEntry logentry = null;
    private File file = null;
    private File folder = null;
    private final JFileChooser filechooser = new JFileChooser();

    /**
     * Creates new form WizardSaveAs
     */
    public WizardSaveAs() {
        initComponents();
        init();
    }
    
    private void init() {
        addWindowListener(this);
        setModal(true);
        filechooser.setMultiSelectionEnabled(false);
        filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        folder = new File(System.getProperty("user.dir"));
    }
    
    public LogEntry showSaveAsDialog(Component c) {
        try {
            textfield_center_path.setText("");
            if(folder != null && folder.exists() && folder.isDirectory()) {
                filechooser.setCurrentDirectory(folder);
            } else {
                folder = new File(System.getProperty("user.dir"));
                filechooser.setCurrentDirectory(folder);
            }
            filechooser.setSelectedFile(new File(""));
        } catch (Exception ex) {
            StaticStandard.logErr("Error while setting showSaveAsDialog: " + ex, ex);
        }
        setLocationRelativeTo(c);
        setVisible(true);
        return finish();
    }
    
    private LogEntry finish() {
        try {
            file = new File(textfield_center_path.getText());
            logentry = new LogEntry(file, Instant.now(), LogEntry.LEVELINPUT, "dd.MM.yyyy HH:mm:ss", null, null);
            logentry.setPrintExtraInformation(checkbox_save_infos_appearance.isSelected());
            logentry.setPrintLevel(checkbox_save_infos_level.isSelected());
            logentry.setPrintTimestamp(checkbox_save_infos_timestamp.isSelected());
            folder = file.getParentFile();
        } catch (Exception ex) {
            logentry = null;
            StaticStandard.logErr("Error while finishing save as: " + ex, ex);
        }
        dispose();
        return logentry;
    }
    
    private void close() {
        logentry = null;
        file = null;
        textfield_center_path.setText("");
        dispose();
    }
    
    public void searchComputer(Component c) {
        int result = filechooser.showSaveDialog(c);
        File file_temp = filechooser.getSelectedFile();
        if(result == JFileChooser.APPROVE_OPTION && file_temp != null) {
            file = file_temp;
            textfield_center_path.setText(file.getAbsolutePath());
        }
    }

    public File getFile() {
        return file;
    }

    public void setFile(File file) {
        this.file = file;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        button_bottom_cancel = new javax.swing.JButton();
        button_bottom_finish = new javax.swing.JButton();
        button_bottom_next = new javax.swing.JButton();
        button_bottom_back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        panel_1 = new javax.swing.JPanel();
        textfield_center_path = new javax.swing.JTextField();
        button_center_path = new javax.swing.JButton();
        label_center_path = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        checkbox_save_level_error = new javax.swing.JCheckBox();
        checkbox_save_level_low = new javax.swing.JCheckBox();
        checkbox_save_level_command = new javax.swing.JCheckBox();
        checkbox_save_level_input = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        label_save_level = new javax.swing.JLabel();
        label_save_infos = new javax.swing.JLabel();
        checkbox_save_infos_level = new javax.swing.JCheckBox();
        checkbox_save_infos_appearance = new javax.swing.JCheckBox();
        checkbox_save_infos_timestamp = new javax.swing.JCheckBox();
        checkbox_save_level_normal = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));

        button_bottom_cancel.setText("Cancel");
        button_bottom_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bottom_cancelActionPerformed(evt);
            }
        });

        button_bottom_finish.setText("Finish");
        button_bottom_finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bottom_finishActionPerformed(evt);
            }
        });

        button_bottom_next.setText("Next >");
        button_bottom_next.setEnabled(false);

        button_bottom_back.setText("< Back");
        button_bottom_back.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(button_bottom_back, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_bottom_next, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_bottom_finish, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_bottom_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_bottom_cancel)
                    .addComponent(button_bottom_finish)
                    .addComponent(button_bottom_next)
                    .addComponent(button_bottom_back))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        button_center_path.setText("Search Computer");
        button_center_path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_center_pathActionPerformed(evt);
            }
        });

        label_center_path.setText("File");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Settings"));

        checkbox_save_level_error.setText("Error");

        checkbox_save_level_low.setText("Low");

        checkbox_save_level_command.setText("Command");

        checkbox_save_level_input.setText("Input");

        label_save_level.setText("Save Level");

        label_save_infos.setText("Save Infos");

        checkbox_save_infos_level.setText("Level");

        checkbox_save_infos_appearance.setText("Appearance");

        checkbox_save_infos_timestamp.setText("Timestamp");

        checkbox_save_level_normal.setText("Normal");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(label_save_level)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkbox_save_level_normal)
                        .addGap(18, 18, 18)
                        .addComponent(checkbox_save_level_error)
                        .addGap(18, 18, 18)
                        .addComponent(checkbox_save_level_low)
                        .addGap(18, 18, 18)
                        .addComponent(checkbox_save_level_command)
                        .addGap(18, 18, 18)
                        .addComponent(checkbox_save_level_input))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(label_save_infos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkbox_save_infos_timestamp)
                        .addGap(18, 18, 18)
                        .addComponent(checkbox_save_infos_appearance)
                        .addGap(18, 18, 18)
                        .addComponent(checkbox_save_infos_level)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkbox_save_level_error)
                    .addComponent(checkbox_save_level_low)
                    .addComponent(checkbox_save_level_command)
                    .addComponent(checkbox_save_level_input)
                    .addComponent(label_save_level)
                    .addComponent(checkbox_save_level_normal))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_save_infos)
                    .addComponent(checkbox_save_infos_level)
                    .addComponent(checkbox_save_infos_appearance)
                    .addComponent(checkbox_save_infos_timestamp))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_1Layout = new javax.swing.GroupLayout(panel_1);
        panel_1.setLayout(panel_1Layout);
        panel_1Layout.setHorizontalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_1Layout.createSequentialGroup()
                        .addComponent(label_center_path, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield_center_path, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_center_path, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_1Layout.setVerticalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_center_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_center_path)
                    .addComponent(label_center_path))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_bottom_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bottom_cancelActionPerformed
        close();
    }//GEN-LAST:event_button_bottom_cancelActionPerformed

    private void button_bottom_finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bottom_finishActionPerformed
        if(textfield_center_path.getText().isEmpty()) {
            return;
        }
        finish();
    }//GEN-LAST:event_button_bottom_finishActionPerformed

    private void button_center_pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_center_pathActionPerformed
        searchComputer(this);
    }//GEN-LAST:event_button_center_pathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WizardSaveAs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WizardSaveAs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WizardSaveAs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WizardSaveAs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WizardSaveAs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton button_bottom_back;
    public javax.swing.JButton button_bottom_cancel;
    public javax.swing.JButton button_bottom_finish;
    public javax.swing.JButton button_bottom_next;
    public javax.swing.JButton button_center_path;
    public javax.swing.JCheckBox checkbox_save_infos_appearance;
    public javax.swing.JCheckBox checkbox_save_infos_level;
    public javax.swing.JCheckBox checkbox_save_infos_timestamp;
    public javax.swing.JCheckBox checkbox_save_level_command;
    public javax.swing.JCheckBox checkbox_save_level_error;
    public javax.swing.JCheckBox checkbox_save_level_input;
    public javax.swing.JCheckBox checkbox_save_level_low;
    public javax.swing.JCheckBox checkbox_save_level_normal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel label_center_path;
    public javax.swing.JLabel label_save_infos;
    public javax.swing.JLabel label_save_level;
    private javax.swing.JPanel panel_1;
    public javax.swing.JTextField textfield_center_path;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
    }

    @Override
    public void windowOpened(WindowEvent e) {
    }

    @Override
    public void windowClosing(WindowEvent e) {
        if(e.getSource() == this) {
            close();
        }
    }

    @Override
    public void windowClosed(WindowEvent e) {
    }

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
    }
}
